site_name: Chironex Design Doc
nav:
    - Home: index.md
    - 'sklearn-estimators':
      - 'Design': 'sklearn-estimators/sklearn-estimators-design.md'
      - 'Usage': 'sklearn-estimators/sklearn-estimators-usage.md'
    - 'jellyfish-system':
      - 'Design': 
        - 'Message': 'jellyfish-system/Design/Message.md'
        - 'Cell': 'jellyfish-system/Design/Cell.md'
        - 'Grid': 'jellyfish-system/Design/Grid.md'
        - 'Learner': 'jellyfish-system/Design/Learner.md'
        - 'Jellyfish': 'jellyfish-system/Design/Jellyfish.md'
        - 'Logger': 'jellyfish-system/Design/Logger.md'
        - 'Engine': 'jellyfish-system/Design/Engine.md'
      - 'Usage': 
        - 'Training and Plotting': 'jellyfish-system/Usage/Training and Plotting.md'
        - "Integration with Atolla's environment": "jellyfish-system/Usage/Integration with Atolla's environment.md"

    - About: about.md
theme: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
