site_name: Chironex Design Doc
nav:
    - Home: index.md
    - Usage: usage.md
    - Design: design.md
    - About: about.md
theme: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
